
name: investly_demo
description: Demo Flutter app for Investly (ready to upload). Light/dark themes, onboarding, dashboard, portfolios, objectives, brokers.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^0.13.5
  url_launcher: ^6.1.7
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
